/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria;

import interfaces.PizzaComponent;
import java.io.File;
import java.lang.reflect.Constructor;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import util.UtilFile;

/**
 *
 * @author jeanp
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        //String[] itemsDecorators = {"Queijo", "Presunto", "Azeitona", "Bacon", "Atum"};
        try {
            ArrayList<String> itemsDecorators = loadPluginDecorator();
            for (int i = 0; i < itemsDecorators.size(); i++) {
                listDecorators.add(itemsDecorators.get(i), i);
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listDecorators = new java.awt.List();
        buttonSelect = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonUp = new javax.swing.JButton();
        buttonDown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGenerate = new javax.swing.JButton();
        listDecoratorsSelecteds = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(listDecorators, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 200));

        buttonSelect.setText(">");
        buttonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        buttonRemove.setText("<");
        buttonRemove.setEnabled(false);
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        buttonUp.setText("Sobe");
        buttonUp.setEnabled(false);
        buttonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 53, 61, -1));

        buttonDown.setText("Desce");
        buttonDown.setEnabled(false);
        buttonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 87, -1, -1));

        jLabel1.setText("Decorators Disponiveis");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, -1, -1));

        jLabel2.setText("Decorators Selecionados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 23, -1, -1));

        buttonGenerate.setText("Gerar");
        buttonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        listDecoratorsSelecteds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDecoratorsSelectedsMouseClicked(evt);
            }
        });
        jPanel1.add(listDecoratorsSelecteds, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 120, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Pizzaria Decorator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectActionPerformed
        listDecoratorsSelecteds.add(listDecorators.getSelectedItem());

        buttonRemove.setEnabled(((!buttonRemove.isEnabled()) && (0 != listDecoratorsSelecteds.getItems().length)
                || (buttonRemove.isEnabled()) && (0 != listDecoratorsSelecteds.getItems().length)));

        if (1 < listDecoratorsSelecteds.getItems().length) {
            buttonUp.setEnabled(true);
            buttonDown.setEnabled(true);
        }
        //buttonGenerate.setEnabled(0 < listDecoratorsSelecteds.getItems().length);

    }//GEN-LAST:event_buttonSelectActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        if (0 <= listDecoratorsSelecteds.getSelectedIndex()) {
            listDecoratorsSelecteds.remove(listDecoratorsSelecteds.getSelectedIndex());

            buttonRemove.setEnabled(!(0 == listDecoratorsSelecteds.getItems().length));
            if (1 >= listDecoratorsSelecteds.getItems().length) {
                buttonUp.setEnabled(false);
                buttonDown.setEnabled(false);
            }
            // buttonGenerate.setEnabled(1 <= listDecoratorsSelecteds.getItems().length);
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Selecione um item adicionado para remover");
        }

    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownActionPerformed
        if (0 <= listDecoratorsSelecteds.getSelectedIndex()) {
            if (!isLastItem()) {
                int indice = listDecoratorsSelecteds.getSelectedIndex();
                String item = listDecoratorsSelecteds.getSelectedItem();
                String itemAux = listDecoratorsSelecteds.getItem(listDecoratorsSelecteds.getSelectedIndex() + 1);
                listDecoratorsSelecteds.remove(indice + 1);
                listDecoratorsSelecteds.add(item, indice + 1);
                listDecoratorsSelecteds.remove(indice);
                listDecoratorsSelecteds.add(itemAux, indice);
                listDecoratorsSelecteds.select(indice + 1);
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Selecione um item adicionado para descer");
        }


    }//GEN-LAST:event_buttonDownActionPerformed

    private void listDecoratorsSelectedsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDecoratorsSelectedsMouseClicked
        buttonDown.setEnabled(!isLastItem());
        buttonUp.setEnabled(!isFirstItem());
    }//GEN-LAST:event_listDecoratorsSelectedsMouseClicked

    private void buttonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpActionPerformed
        if (0 <= listDecoratorsSelecteds.getSelectedIndex()) {
            if (!isFirstItem()) {
                int indice = listDecoratorsSelecteds.getSelectedIndex();
                String item = listDecoratorsSelecteds.getSelectedItem();
                String itemAux = listDecoratorsSelecteds.getItem(indice - 1);
                listDecoratorsSelecteds.remove(indice - 1);
                listDecoratorsSelecteds.add(item, indice - 1);
                listDecoratorsSelecteds.remove(indice);
                listDecoratorsSelecteds.add(itemAux, indice);
                listDecoratorsSelecteds.select(indice - 1);
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Selecione um item adicionado para subir");
        }
    }//GEN-LAST:event_buttonUpActionPerformed

    private void buttonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateActionPerformed
        final Integer SIM = 0;
        Icon errorIcon = UIManager.getIcon("OptionPane.errorIcon");
        Object[] possibilities = {"Sim", "Não"};
        Integer resposta = (Integer) JOptionPane.showOptionDialog(jPanel1,
                "Confirmar a geração da pizza?", "Pizzaria Decorator",
                JOptionPane.YES_NO_OPTION, 1, errorIcon, possibilities, 0);

        if (0 == resposta.compareTo(SIM)) {

            PizzaComponent pizza = null;
            String[] itemsPizza = listDecoratorsSelecteds.getItems();
            ArrayList<Class> itemsDecorator = new ArrayList<>();

            if (0 == itemsPizza.length) {
                pizza = new PizzaBasica();
            } else {
                for (String item : itemsPizza) {
                    item = "decorators." + item + "Decorator";
                    try {
                        Class metadecorator = Class.forName(item, true, ulc);
                        itemsDecorator.add(metadecorator);
                    } catch (Exception ex) {
                        System.err.println(ex.getMessage());
                    }
                }

                for (int j = (itemsDecorator.size() - 1); j >= 0; j--) {
                    try {
                        Constructor itemConstrucor = itemsDecorator.get(j).getConstructor(PizzaComponent.class);
                        if (j == (itemsDecorator.size() - 1)) {
                            pizza = (PizzaComponent) itemConstrucor.newInstance(new PizzaBasica());
                        } else {
                            pizza = (PizzaComponent) itemConstrucor.newInstance(pizza);
                        }
                    } catch (Exception ex) {
                        System.err.println(ex.getMessage());
                    }
                }
            }

            pizza.preparar();
            System.out.println("Pizza Gerada com Sucesso");
            System.out.println("");
            JOptionPane.showMessageDialog(jPanel1, "Pizza Gerada com Sucesso");
        }
    }//GEN-LAST:event_buttonGenerateActionPerformed

    private boolean isLastItem() {
        return listDecoratorsSelecteds.getSelectedIndex() == (listDecoratorsSelecteds.getItems().length - 1);
    }

    private boolean isFirstItem() {
        return 0 == listDecoratorsSelecteds.getSelectedIndex();
    }

    private ArrayList<String> loadPluginDecorator() throws Exception {
        String[] plugins = UtilFile.getAllPlugins();
        ArrayList<String> pluginsName = new ArrayList<>();

        int i;
        URL[] jars = new URL[plugins.length];
        for (i = 0; i < plugins.length; i++) {
            jars[i] = (new File("./plugins/" + plugins[i])).toURL();
        }
        ulc = new URLClassLoader(jars);
        for (int j = 0; j < plugins.length; j++) {
            pluginsName.add(UtilFile.getDecoratorPlugin(plugins[j]));
        }
        return pluginsName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    private URLClassLoader ulc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDown;
    private javax.swing.JButton buttonGenerate;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSelect;
    private javax.swing.JButton buttonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.List listDecorators;
    private java.awt.List listDecoratorsSelecteds;
    // End of variables declaration//GEN-END:variables
}
